name: SHRP CIRRUS CI
on:
  workflow_dispatch:
  
jobs:
  cirrus:
    runs-on: ubuntu-latest
    permissions:
     actions: write|read
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: SHRP CIRRUS CI
      uses: cirruslabs/cirrus-action@v2
